# Generated by Django 6.0 on 2026-01-13 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_company_address'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='warehouse',
            unique_together={('company', 'name')},
        ),
    ]
