# Generated by Django 6.0 on 2026-01-18 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_alter_warehouse_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
