# Generated by Django 6.0 on 2026-01-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorystock',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
