# Generated by Django 6.0 on 2026-01-13 08:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_company_address'),
        ('inventory', '0002_alter_inventorystock_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryOrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('unit', models.CharField(max_length=20)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.inventoryorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.product')),
            ],
        ),
    ]
