# Generated by Django 6.0 on 2025-12-27 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('inventory', '0002_inventoryadjustment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryadjustment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.product'),
        ),
        migrations.AlterField(
            model_name='inventorystock',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.product'),
        ),
        migrations.AlterField(
            model_name='inventoryledger',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.product'),
        ),
        migrations.AlterField(
            model_name='inventoryadjustment',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.warehouse'),
        ),
        migrations.AlterField(
            model_name='inventoryledger',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.warehouse'),
        ),
        migrations.AlterField(
            model_name='inventorystock',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.warehouse'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Warehouse',
        ),
    ]
