# Generated by Django 6.0 on 2026-01-13 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventoryorderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryorder',
            name='delta',
        ),
        migrations.RemoveField(
            model_name='inventoryorder',
            name='product',
        ),
    ]
