# Generated by Django 6.0 on 2026-01-01 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_inventoryissue'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryissue',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryissue',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rejected_issues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventoryissue',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
    ]
