# Generated by Django 6.0 on 2026-01-15 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_inventoryorder_received_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryorder',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RECEIVED', 'Received')], default='PENDING', max_length=20),
        ),
    ]
