# Generated by Django 6.0 on 2026-01-16 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_alter_warehouse_unique_together'),
        ('inventory', '0006_alter_inventoryorder_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryorder',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='company.supplier'),
        ),
    ]
