# Generated by Django 6.0 on 2026-01-16 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_alter_warehouse_unique_together'),
        ('inventory', '0007_inventoryorder_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryorder',
            name='supplier',
            field=models.ForeignKey(default='f4846047-f47a-4176-9b17-183a7f487553', on_delete=django.db.models.deletion.PROTECT, to='company.supplier'),
            preserve_default=False,
        ),
    ]
