# Generated by Django 6.0 on 2026-01-22 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_inventoryissue_quantity_goodsreceiptnote_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryissue',
            name='issue_slip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='inventory.issueslip'),
        ),
        migrations.AlterField(
            model_name='inventoryorder',
            name='pr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='inventory.purchaserequisition'),
        ),
    ]
