# Generated by Django 6.0 on 2026-01-22 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_alter_warehouse_location'),
        ('inventory', '0010_alter_inventoryissue_issue_slip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequisition',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20),
        ),
        migrations.CreateModel(
            name='IssueSlipItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.product')),
                ('slip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.issueslip')),
            ],
        ),
    ]
