# Generated by Django 6.0 on 2026-01-25 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_alter_warehouse_location'),
        ('core', '0002_remove_auditlog_actor_id_auditlog_actor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='company',
            field=models.ForeignKey(default='f8104f14-a08b-4498-b585-e315c8a9218b', on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='company.company'),
            preserve_default=False,
        ),
    ]
